version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  php:
    container_name: php_phalcon_test
    image: authus/phalcon:5.8.0
    #image: registry.cn-shenzhen.aliyuncs.com/authus/phalcon:5.7.0
    working_dir: /var/www
    volumes:
      - ./src:/var/www:delegated
      - ./log/php:/var/log/php/:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: "serverName=docker-php"
    env_file:
      - .env

  mysql:
    container_name: mysql_phalcon_test
    image: mysql:8.1.0
    ports:
      - "${MYSQL_PORT}:3306"
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_0900_ai_ci'
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d
      - ./log/mysql:/var/log/mysql/:rw
    restart: always
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_phalcon_test
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_phalcon_test
    ports:
      - '${OPEN_PORT}:80'
    restart: on-failure
    volumes:
      - ./src:/var/www
      - ./nginx/location.conf:/etc/nginx/location.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx/:rw
    networks:
      - backend
    links:
      - php